# === MariaDB ===
spring.datasource.url=jdbc:mariadb://localhost:3306/kcdformes
spring.datasource.username=kcdformes
spring.datasource.password=kcdformes2026
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# === H2 désactivé en prod ===
spring.h2.console.enabled=false